// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG6LVc36Wb490zanV1uEQ9t-g8h6Ieh20',
    appId: '1:1083250823414:web:091d47b39d3aaddceedcd7',
    messagingSenderId: '1083250823414',
    projectId: 'fir-flutter-petshop',
    authDomain: 'fir-flutter-petshop.firebaseapp.com',
    storageBucket: 'fir-flutter-petshop.appspot.com',
    measurementId: 'G-ZXTBY4EP12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSjfe_jfe6e3sB4fAZuVNwJAJ_dozoOTQ',
    appId: '1:1083250823414:android:fccd56506970df46eedcd7',
    messagingSenderId: '1083250823414',
    projectId: 'fir-flutter-petshop',
    storageBucket: 'fir-flutter-petshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJmyiBrE1UwCY-zANDMYeTG95QlDgFEM',
    appId: '1:1083250823414:ios:fa2362b35845fbbeeedcd7',
    messagingSenderId: '1083250823414',
    projectId: 'fir-flutter-petshop',
    storageBucket: 'fir-flutter-petshop.appspot.com',
    iosClientId: '1083250823414-bnv2g72cin4drcpr54m0ugl1kgatmume.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJmyiBrE1UwCY-zANDMYeTG95QlDgFEM',
    appId: '1:1083250823414:ios:fa2362b35845fbbeeedcd7',
    messagingSenderId: '1083250823414',
    projectId: 'fir-flutter-petshop',
    storageBucket: 'fir-flutter-petshop.appspot.com',
    iosClientId: '1083250823414-bnv2g72cin4drcpr54m0ugl1kgatmume.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUi',
  );
}
